
@quiz = Quiz.create(title: 'Which boba tea drink are you?', user_id: 1, public: true, featured: true)
@quiz.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/boba.jpg'), filename: 'boba/boba.jpg', content_type: 'application/jpg')
current_quiz_id = @quiz.id
@result = Result.create(title: 'Brown Sugar Milk Tea', description: 'You are a natural sweet tooth and seek the flamboyant fun in life. You never cease to try new things, always entertaining the inner adrenaline junkie inside you, and are energized by being at parties and around crowds of people. You have a fun-loving view of life, where the happiness of yourself and the people you love is your utmost importance.', weight: 1, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/brown_sugar_boba.png'), filename: 'boba/brown_sugar_boba.png', content_type: 'application/png')
@result = Result.create(title: 'Matcha Milk Tea', description: 'You are the token “hard worker” of the group––most likely to be voted as “employee of the month” or always the top student of the class. You are constantly searching for new challenges or creative projects to invest in, and though you may initially be seen as unrelenting and aloof, people come to realize your sensitive and caring side for others.', weight: 2, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/matcha_boba.jpg'), filename: 'boba/matcha_boba.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Thai Milk Tea', description: 'You are an idealist, whether that be spending mornings daydreaming or losing yourself in the world of fiction. You like to be inspired by reading books, watching home makeovers, browsing interior designs, or online shopping. As you are very open about your thoughts and feelings, you are grateful when others reciprocate the same level of trust and honesty.', weight: 3, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/thai_tea_boba.jpg'), filename: 'boba/thai_tea_boba.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Taro Milk Tea', description: 'You are an unpredictable mystery. You frequently like unpopular things, and gravitate away from the crowd-followed trends, as you value being honest to your own interests and opinions. You not only have a uniquely contagious laugh and smile that radiates warmth and happiness, but also possess a dark edgier side that adds to your charm.', weight: 4, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/taro_boba.jpg'), filename: 'boba/taro_boba.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Cheese Foam Milk Tea', description: 'You are the joker! You have a great sense of humor and find any opportunity to make others laugh, as you feel deeply uncomfortable in unnerving silence and tension. Given your comedic talents, it is no surprise that you are observant, quick-witted, and spontaneous, often making questionable life decisions that make for hilarious stories for your friends.', weight: 5, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/cheese_foam_boba.jpg'), filename: 'boba/cheese_foam_boba.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Mango Green Tea', description: 'You are the classic girl/boy next door, charming and likable yet pure and modest. With a daring fashion sense and style, you might seem intimidating at first, but people will be drawn to your approachable smile. Your hobbies include painting, baking, gardening, or taking yourself on a romantic trip to a new city, as you find joy in spending time alone.', weight: 6, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/mango_green_tea.jpg'), filename: 'boba/mango_green_tea.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Passion Fruit Black Tea', description: 'You are the life of the party, as an extroverted and warm-hearted individual. You love going on social outings and despite your social butterfly tendencies, value the loyal presence of your closest friends. Like that girl you stumble upon in bathroom lines at the club, you are always there to hype others up, uplifting and supporting everyone around you.', weight: 7, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/passion_fruit_black_tea.jpg'), filename: 'boba/passion_fruit_black_tea.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What does your ideal weekend look like?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Partying at the club', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/partying_club.jpg'), filename: 'boba/partying_club.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Cozying up with a new book', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/reading_books.png'), filename: 'boba/reading_books.png', content_type: 'application/png')
@choice = Choice.create(content: 'Playing games with friends', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/board_games.jpg'), filename: 'boba/board_games.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Drawing or painting', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/painting.jpg'), filename: 'boba/painting.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Hiking a new trail', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/hiking.jpg'), filename: 'boba/hiking.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Catching up on a TV show', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/watching_tv.jpg'), filename: 'boba/watching_tv.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Going shopping at the mall', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/shopping_mall.jpg'), filename: 'boba/shopping_mall.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What genre of movies or TV shows do you enjoy the most?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Horror or mystery', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/horror.jpg'), filename: 'boba/horror.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Action or superhero', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/action_superhero.jpg'), filename: 'boba/action_superhero.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Romantic chick-flick', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/chick_flick.jpg'), filename: 'boba/chick_flick.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Comedy show', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/comedy.jpg'), filename: 'boba/comedy.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Animated film', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/disney_pixar.jpg'), filename: 'boba/disney_pixar.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Musical', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/musical.jpg'), filename: 'boba/musical.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Sci-fi thriller', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/ex_machina.jpg'), filename: 'boba/ex_machina.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'If you could time travel backwards or forwards, where would you go?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'The Wall-E future: how far can technology go?', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/wall_e.jpg'), filename: 'boba/wall_e.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'The end of time: if that even exists', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/end_of_time.jpg'), filename: 'boba/end_of_time.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Birth of industrialization: ingenious inventions', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/industrialization.jpg'), filename: 'boba/industrialization.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Stone age: the hard-knock life', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/stone_age.jpg'), filename: 'boba/stone_age.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Vikings and voyages: discovering new lands', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/vikings.jpg'), filename: 'boba/vikings.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Roaring Twenties: party party party!', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/roaring_twenties.jpg'), filename: 'boba/roaring_twenties.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Renaissance: I’m a patron of the arts', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/renaissance.jpg'), filename: 'boba/renaissance.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What do you look for the most in a best friend?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Brutal honesty', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'Sense and intellect', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'Good listener', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'Same sense of humor', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'Fun-loving and shared interests', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Matches your style', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'Loyalty and emotional presence', weight: 7, question_id: current_question_id)
@question = Question.create(title: 'Which smell or fragrance appeals to you the most?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Freshly baked cookies', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/freshly_baked_cookies.jpg'), filename: 'boba/freshly_baked_cookies.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Rose petals and flowers', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/rose_petals_perfume.jpg'), filename: 'boba/rose_petals_perfume.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Burnt wood fireplace', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/wood_fireplace.jpg'), filename: 'boba/wood_fireplace.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Salty beach waves', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/beach_waves.jpg'), filename: 'boba/beach_waves.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Fruits and citrus', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/citrus_fruits.jpeg'), filename: 'boba/citrus_fruits.jpeg', content_type: 'application/jpeg')
@choice = Choice.create(content: 'Toasty hot chocolate', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/hot_chocolate.jpg'), filename: 'boba/hot_chocolate.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Peppermint spices', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/peppermint_mocha.jpg'), filename: 'boba/peppermint_mocha.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What are your hardest-to-swallow pills?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'You can’t stand silence in a conversation', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'You act confident but seek constant validation from other people', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'You always compliment others while deep-down you’re insecure', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'You idealize relationships but have commitment issues', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'You like being independent because you only care about yourself', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'You like unpopular things because it makes you feel cooler than others', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'You have to work hard because you can’t afford not to', weight: 2, question_id: current_question_id)
@question = Question.create(title: 'You and a friend get into a heated argument. What do you do?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Continue to one-up your friend’s attacks', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Apologize profusely and ask what’s wrong', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'Defend and determinedly justify your emotions', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'Proceed calmly and use a leveled tone of voice', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'Be completely honest about how the argument makes you feel', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'Crack some lighthearted jokes to ease the tension', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'Use reasoning to evaluate each side of the argument', weight: 2, question_id: current_question_id)
@question = Question.create(title: 'Which Asian fast food snack would you like with your boba?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Popcorn chicken', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/popcorn_chicken.jpg'), filename: 'boba/popcorn_chicken.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Waffle fries', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/waffle_fries.jpg'), filename: 'boba/waffle_fries.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Sweet potato fries', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/sweet_potato_fries.jpg'), filename: 'boba/sweet_potato_fries.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Korean cheese hot dogs', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/korean_cheese_corn_dogs.jpg'), filename: 'boba/korean_cheese_corn_dogs.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Chinese fried dough stick', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/you_tiao.jpg'), filename: 'boba/you_tiao.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Beef skewers', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/beef_skewers.jpg'), filename: 'boba/beef_skewers.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Spring rolls', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/spring_rolls.jpg'), filename: 'boba/spring_rolls.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What is your average sweetness level that you ask for in your tea?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: '200%: sugar is more important than tea', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: '100%: I like sugar!', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: '70%: I try to control my sugar intake', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: '50%: a perfect mathematical balance', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: '30%: I like a little bitterness', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: '0%: I just want the tea', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'I don’t specify the sweetness', weight: 4, question_id: current_question_id)
@question = Question.create(title: 'What is your favorite boba drink topping?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Aloe vera', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/aloe_vera.jpg'), filename: 'boba/aloe_vera.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Boba', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/pearls.jpg'), filename: 'boba/pearls.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Pudding', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/pudding.jpg'), filename: 'boba/pudding.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Grass jelly', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/grass_jelly.jpg'), filename: 'boba/grass_jelly.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Red bean', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/red_bean.jpg'), filename: 'boba/red_bean.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Mango stars', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/mango_stars.jpg'), filename: 'boba/mango_stars.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'No toppings', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/boba/no_toppings.jpg'), filename: 'boba/no_toppings.jpg', content_type: 'application/jpg')

@quiz = Quiz.create(title: 'What color are you?', user_id: 1, public: true, featured: true)
@quiz.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/colors.jpg'), filename: 'colors/colors.jpg', content_type: 'application/jpg')
current_quiz_id = @quiz.id
@result = Result.create(title: 'White', description: 'You are kind, pure, and clean. Comforting like the soft snow and a clean white T-shirt, you emanate an aura of kindness and honesty. You have an innocent beauty that blooms like white blossoms, drawing endless love and admiration.', weight: 1, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/white.jpg'), filename: 'colors/white.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Red', description: 'You are aggressive, passionate, and assertive. Your emotions and thoughts spread like wildfire, igniting those around you. You love deep and hard, as red symbolizes the vivid color of lips and richness of blood pumping through our hearts.', weight: 2, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/red.jpg'), filename: 'colors/red.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Orange', description: 'You are spontaneous, wild, and cheerful. You like to let go of the rigidities in life and jump into piles of warm autumn leaves. You are best friends with a Red, or transitioning to one yourself, likely because of your bright and fervent passion.', weight: 3, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/orange.jpg'), filename: 'colors/orange.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Yellow', description: 'You are active, positive, and friendly. Your inspiring energy is blinding like the sun, and you spread warmth to everyone around you. You are approachable and easygoing, like a welcoming meadow filled with sunflowers and yellow daffodils.', weight: 4, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/yellow.jpg'), filename: 'colors/yellow.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Green', description: 'You are reliable, wise, and responsible. As sturdy as a redwood but flexible as a willow, you are smart and well-rounded in your actions. Your unwavering faith and commitment are like evergreen trees, steady through seasons of hardship.', weight: 5, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/green.jpg'), filename: 'colors/green.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Blue', description: 'You are trustworthy, intelligent, and confident. Your knowledge is as vast as the blue sky and the ocean, and you are self-assured in your answers. People place immense trust in you and gravitate towards your dependable charisma.', weight: 6, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/blue.jpg'), filename: 'colors/blue.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Purple', description: 'You are gentle, supportive, and sensitive. You are light and pleasant like lavender and tender like the flesh of sweet potatoes. You bring out the best in others, like the strong and vibrant pigment in beets, plums, and dark cherries.', weight: 7, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/purple.jpg'), filename: 'colors/purple.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Gray', description: 'You are temperate, graceful, and protective. You are calm and moderate with things in life, and neat and dignified with your style. As an affectionate and loving person, you are the clouds that shield others from harm and shower them with love. ', weight: 8, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/gray.jpg'), filename: 'colors/gray.jpg', content_type: 'application/jpg')
@result = Result.create(title: 'Black', description: 'You are powerful, elegant, and mysterious. You command the respect of others with your formidable power and puzzling secrets. Like smooth obsidian and ebony or the night sky sprinkled with stars, you are stylish and sophisticated.', weight: 9, quiz_id: current_quiz_id)
@result.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/black.jpg'), filename: 'colors/black.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'How would your friends best describe you?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Super nice to everyone', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Loud and overzealous', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'Sees the bright side of everything', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'Understanding and empathetic', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'Smart and knowledgeable', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'Intimidating and strong', weight: 9, question_id: current_question_id)
@choice = Choice.create(content: 'A motherly figure', weight: 8, question_id: current_question_id)
@choice = Choice.create(content: 'Unpredictable, always going places', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'Can always count on you', weight: 5, question_id: current_question_id)
@question = Question.create(title: 'What genre of music do you listen to the most?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Dance and EDM', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/dance_edm.jpg'), filename: 'colors/dance_edm.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Soul and R&B', weight: 9, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/soul_rnb.jpg'), filename: 'colors/soul_rnb.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Movie soundtracks', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/movie.jpg'), filename: 'colors/movie.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Gentle jazz', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/jazz.jpg'), filename: 'colors/jazz.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Classical', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/classical.jpg'), filename: 'colors/classical.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Pop and upbeat songs', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/pop.jpg'), filename: 'colors/pop.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Indie and folk', weight: 8, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/indie.jpg'), filename: 'colors/indie.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Literally anything', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/any_song.jpg'), filename: 'colors/any_song.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Trap and hip-hop', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/trap_hiphop.jpg'), filename: 'colors/trap_hiphop.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What is your sense of style?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Bold and scandalous', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/scandalous.jpeg'), filename: 'colors/scandalous.jpeg', content_type: 'application/jpeg')
@choice = Choice.create(content: 'Neon and bright colors', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/neon.jpg'), filename: 'colors/neon.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Comfy loungewear', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/loungewear.jpg'), filename: 'colors/loungewear.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Classy and chic', weight: 9, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/classy.jpg'), filename: 'colors/classy.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Clean and minimalist', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/minimalist.jpg'), filename: 'colors/minimalist.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Monochrome outfits', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/purple_monochrome.jpeg'), filename: 'colors/purple_monochrome.jpeg', content_type: 'application/jpeg')
@choice = Choice.create(content: 'Vintage fashion', weight: 8, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/vintage.jpg'), filename: 'colors/vintage.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Artsy and experimental', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/artsy.jpg'), filename: 'colors/artsy.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Denim, denim, denim', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/denim.jpg'), filename: 'colors/denim.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'What would your dream vacation be like?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Bungee jumping or skydiving over the Swiss Alps', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/skydiving.jpg'), filename: 'colors/skydiving.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Trekking through a cloud forest in Costa Rica', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/cloud_forest.jpg'), filename: 'colors/cloud_forest.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Going on a picnic at the beach in Hawaii', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/picnic_beach.jpg'), filename: 'colors/picnic_beach.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Camping with your friends or family in Yosemite', weight: 8, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/yosemite_camping.jpg'), filename: 'colors/yosemite_camping.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Walking the glass bridge in Zhangjiajie', weight: 9, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/glass_bridge.jpg'), filename: 'colors/glass_bridge.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Going skiing or snowboarding at a Reno resort', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/ski_resort.jpg'), filename: 'colors/ski_resort.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Last-minute decisions; who knows!', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/question_mark.jpg'), filename: 'colors/question_mark.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Visiting a botanical garden in London', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/botanical_garden.jpg'), filename: 'colors/botanical_garden.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Riding a gondola through Venice', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/gondola.jpeg'), filename: 'colors/gondola.jpeg', content_type: 'application/jpeg')
@question = Question.create(title: 'There is an extra hour in the day. How do you spend it?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Go shopping for some gifts for family and friends', weight: 7, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/shopping_gifts.jpg'), filename: 'colors/shopping_gifts.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Cook a nice and healthy meal for others', weight: 8, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/cook_meals.jpg'), filename: 'colors/cook_meals.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Get a head start on work or side projects', weight: 5, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/work.jpg'), filename: 'colors/work.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Do your laundry, vacuum the house, and reorganize your closet', weight: 1, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/cleaning.jpg'), filename: 'colors/cleaning.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'I don’t usually plan out how I will spend my day', weight: 3, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/no_plan.jpg'), filename: 'colors/no_plan.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Read a news article or catch up on books', weight: 6, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/reading.jpg'), filename: 'colors/reading.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Hit up all your friends and throw a party', weight: 2, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/party.jpg'), filename: 'colors/party.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'Go to the gym or go hiking at a local park', weight: 4, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/workout.jpg'), filename: 'colors/workout.jpg', content_type: 'application/jpg')
@choice = Choice.create(content: 'It is a secret', weight: 9, question_id: current_question_id)
@choice.image.attach(io: File.open(Rails.root.to_s + '/app/assets/images/colors/secret.jpg'), filename: 'colors/secret.jpg', content_type: 'application/jpg')
@question = Question.create(title: 'If you could give advice to your younger self, what would it be?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Being kind always rewards you in the end', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Never stop learning and challenging yourself', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'Remember, less is more in life', weight: 8, question_id: current_question_id)
@choice = Choice.create(content: 'Stay true to yourself and your loved ones', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'Live life in the moment and don’t worry about the future', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'You miss 100% of the shots you don’t take', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'Treat others the way you want to be treated', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'Always make friends wherever you go', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'With great power comes great responsibility', weight: 9, question_id: current_question_id)
@question = Question.create(title: 'Someone you love is going through a hard time. What do you do?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Tell a joke or funny story', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'Give them a shoulder to lean on', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'Rationalize their thoughts and feelings', weight: 6, question_id: current_question_id)
@choice = Choice.create(content: 'Listen intently and empathize', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'Make them their favorite food', weight: 8, question_id: current_question_id)
@choice = Choice.create(content: 'Give them warm hugs', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Try anything to cheer them up', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'Take them out to drink away their sorrows', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'Show them little signs of your love', weight: 9, question_id: current_question_id)
@question = Question.create(title: 'What brings you the most discomfort?', quiz_id: current_quiz_id)
current_question_id = @question.id
@choice = Choice.create(content: 'Knowing you can’t be there for someone', weight: 8, question_id: current_question_id)
@choice = Choice.create(content: 'Being exposed or stripped of power', weight: 9, question_id: current_question_id)
@choice = Choice.create(content: 'Having few or no friends', weight: 4, question_id: current_question_id)
@choice = Choice.create(content: 'Losing your sense of direction in life', weight: 5, question_id: current_question_id)
@choice = Choice.create(content: 'Seeing people get hurt', weight: 1, question_id: current_question_id)
@choice = Choice.create(content: 'Feeling bored and uninspired', weight: 2, question_id: current_question_id)
@choice = Choice.create(content: 'Being controlled by others', weight: 3, question_id: current_question_id)
@choice = Choice.create(content: 'Saying something you regret', weight: 7, question_id: current_question_id)
@choice = Choice.create(content: 'Not being able to solve a problem', weight: 6, question_id: current_question_id)

